apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-red
spec:
  containers:
  - name: nginx
    image: nginx:latest
  tolerations:
  - key: "color"
    operator: "Equal"
    value: "red"
    effect: "NoSchedule"

