apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab17
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: lab17
  template:
    metadata:
      labels:
        app: lab17
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: lab17
        ports:
        - containerPort: 80
