apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: nti
spec:
  hard:
    pods: "4"
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"

